### ISSUE TITLE
hanging on macOS

### ISSUE THREAD

**Issue by evilsocket** [bettercap/gatt#1]
The library is hanging on macOS High Sierra (latest), after some debugging, [this message](https://github.com/bettercap/gatt/blob/master/device_darwin.go#L73) is correctly sent but no response is received [on this channel](https://github.com/bettercap/gatt/blob/master/device_darwin.go#L513), probably some of those XPC constants/structures/types changed.

idk ¯\\\_(ツ)\_/¯

**Comment by ghost** [comment]
https://github.com/noble/bleno/pull/360 is probably the right place to start, so I'll just leave it here.

**Comment by secit-pl** [comment]
Any update on this?

**Comment by evilsocket** [comment]
do you see any? :)

**Comment by secit-pl** [comment]
Nope, that's why I asked ¯\\\_(ツ)_/¯

**Comment by raff** [comment]
A couple of things:
1) the XPC package is a copy/adaptation of my XPC package that you can now just import directly from "github.com/raff/goble/xpc" (if you do and find any problem, just create an issue or open a PR)
2) I am trying to keep up with MacOS changing the XPC codes for Bluetooth on every release, so you may look at some of the changes here: https://github.com/raff/goble/commits/master/goble.go

Finally, MacOS now exposes "real" Bluetooth APIs and there is a pull request in "noble" that add support for that (https://github.com/noble/noble/pull/840). I had a look at it, to see how easy it would be to re-use their low-level implementation, but it's in C++ and was a little more work than I wanted to do.

**Comment by raff** [comment]
Actually, to be more specific, in https://github.com/bettercap/gatt/blob/master/device_darwin.go#L393 you are checking for 6 (state changed). But at some point in history, the code for "state changed" became 4. See https://github.com/raff/goble/commit/fadc3db9f77abd3b8036a54d4373c7a71030ddac
