### ISSUE TITLE
Bug in asm.s breaks build

### ISSUE THREAD

**Issue by fabianfrz** [bettercap/gatt#2]
A bug in this library breaks the build of bettercap:

```
LC_ALL=en_US.utf8 go get github.com/bettercap/bettercap
# github.com/bettercap/gatt/linux/socket
go/src/github.com/bettercap/gatt/linux/socket/asm.s:5:10: fatal error: textflag.h: No such file or directory
 #include "textflag.h"
          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by buffermet** [comment]
What version of Go are you using?

Please write a complete issue...

**Comment by evilsocket** [comment]
Incomplete report, i'm sick of this, people are either too lazy or too dumb to understand without details about Go version, OS, etc we just can't understand what they're talking about.
